apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: error-handling
spec:
  steps:
  - name: create-invalid-job-template
    try:
    - apply:
        file: ../resources/invalid-job-template.yaml
    - assert:
        file: ../resources/invalid-job-template.yaml
    
  - name: create-pod-to-trigger-invalid-template
    try:
    - apply:
        file: ../resources/test-pod.yaml
    - assert:
        file: ../resources/test-pod.yaml
    
  - name: wait-for-controller-recovery
    try:
    - sleep:
        duration: 10s
  
  - name: verify-controller-running
    try:
    - script:
        content: |
          #!/bin/bash
          set -e
          # Check if controller is still running despite invalid template
          STATUS=$(kubectl get pods -n kubanana-system -l app=kubanana-controller -o jsonpath='{.items[0].status.phase}')
          if [ "$STATUS" = "Running" ]; then
            echo "Controller still running after invalid template: $STATUS"
            exit 0
          else
            echo "Controller not running: $STATUS"
            exit 1
          fi
          
  - name: create-valid-template-after-error
    try:
    - apply:
        file: ../resources/recovery-job-template.yaml
    - assert:
        file: ../resources/recovery-job-template.yaml
    
  - name: create-pod-for-recovery-test
    try:
    - apply:
        file: ../resources/recovery-test-pod.yaml
    - assert:
        file: ../resources/recovery-test-pod.yaml
    
  - name: verify-recovery-job-created
    try:
    - assert:
        file: ../verifications/recovery-job-created.yaml