apiVersion: v1
kind: Namespace
metadata:
  name: kubevent-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevent-controller
  namespace: kubevent-system
  labels:
    app: kubevent-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubevent-controller
  template:
    metadata:
      labels:
        app: kubevent-controller
    spec:
      serviceAccountName: kubevent-sa
      containers:
      - name: controller
        image: kubevent-controller:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi