apiVersion: v1
kind: Namespace
metadata:
  name: kubanana-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubanana-controller
  namespace: kubanana-system
  labels:
    app: kubanana-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubanana-controller
  template:
    metadata:
      labels:
        app: kubanana-controller
    spec:
      serviceAccountName: kubanana-sa
      containers:
      - name: controller
        image: kubanana-controller:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi