apiVersion: v1
kind: Namespace
metadata:
  name: kubevent-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevent-sa
  namespace: kubevent-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevent-role
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["kubevent.roshanbhatia.com"]
  resources: ["eventtriggeredjobs", "eventtriggeredjobs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevent-role-binding
subjects:
- kind: ServiceAccount
  name: kubevent-sa
  namespace: kubevent-system
roleRef:
  kind: ClusterRole
  name: kubevent-role
  apiGroup: rbac.authorization.k8s.io