{{- if .Values.installCRDs }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eventtriggeredjobs.kubanana.roshanbhatia.com
  labels:
    app.kubernetes.io/name: {{ include "kubanana.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  group: kubanana.roshanbhatia.com
  names:
    kind: EventTriggeredJob
    listKind: EventTriggeredJobList
    plural: eventtriggeredjobs
    shortNames:
    - etj
    singular: eventtriggeredjob
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              eventSelector:
                properties:
                  eventTypes:
                    items:
                      enum:
                      - CREATE
                      - UPDATE
                      - DELETE
                      type: string
                    type: array
                  labelSelector:
                    properties:
                      matchExpressions:
                        items:
                          properties:
                            key:
                              type: string
                            operator:
                              type: string
                            values:
                              items:
                                type: string
                              type: array
                          required:
                          - key
                          - operator
                          type: object
                        type: array
                      matchLabels:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  namePattern:
                    type: string
                  namespacePattern:
                    type: string
                  resourceKind:
                    type: string
                type: object
              statusSelector:
                properties:
                  conditions:
                    items:
                      properties:
                        status:
                          type: string
                        type:
                          type: string
                      required:
                      - status
                      - type
                      type: object
                    type: array
                  labelSelector:
                    properties:
                      matchExpressions:
                        items:
                          properties:
                            key:
                              type: string
                            operator:
                              type: string
                            values:
                              items:
                                type: string
                              type: array
                          required:
                          - key
                          - operator
                          type: object
                        type: array
                      matchLabels:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  namePattern:
                    type: string
                  namespacePattern:
                    type: string
                  resourceKind:
                    type: string
                required:
                - resourceKind
                type: object
              jobTemplate:
                properties:
                  metadata:
                    type: object
                  spec:
                    properties:
                      activeDeadlineSeconds:
                        format: int64
                        type: integer
                      backoffLimit:
                        format: int32
                        type: integer
                      completionMode:
                        type: string
                      completions:
                        format: int32
                        type: integer
                      manualSelector:
                        type: boolean
                      parallelism:
                        format: int32
                        type: integer
                      podFailurePolicy:
                        properties:
                          rules:
                            items:
                              properties:
                                action:
                                  type: string
                                onExitCodes:
                                  properties:
                                    containerName:
                                      type: string
                                    operator:
                                      type: string
                                    values:
                                      items:
                                        format: int32
                                        type: integer
                                      type: array
                                  required:
                                  - values
                                  type: object
                                onPodConditions:
                                  items:
                                    properties:
                                      status:
                                        type: string
                                      type:
                                        type: string
                                    required:
                                    - status
                                    - type
                                    type: object
                                  type: array
                              required:
                              - action
                              type: object
                            type: array
                        required:
                        - rules
                        type: object
                      podReplacementPolicy:
                        type: string
                      suspend:
                        type: boolean
                      template:
                        properties:
                          metadata:
                            type: object
                          spec:
                            type: object
                        type: object
                      ttlSecondsAfterFinished:
                        format: int32
                        type: integer
                    required:
                    - template
                    type: object
                type: object
            required:
            - jobTemplate
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true
{{- end }}