apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubanana-controller
  namespace: {{ .Values.namespace.name }}
  labels:
    app: kubanana-controller
    app.kubernetes.io/name: {{ include "kubanana.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: kubanana-controller
  template:
    metadata:
      labels:
        app: kubanana-controller
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: controller
        image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}