apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: label-selector-test
spec:
  steps:
  - name: create-event-based-job-template-with-label-selector
    try:
    - apply:
        file: ../resources/label-selector-job-template.yaml
    - assert:
        file: ../resources/label-selector-job-template.yaml
  
  - name: create-matching-pod
    try:
    - apply:
        file: ../resources/matching-label-pod.yaml
    
  - name: verify-job-creation
    try:
    - assert:
        file: ../verifications/label-selector-job-created.yaml
  
  - name: create-non-matching-pod
    try:
    - apply:
        file: ../resources/non-matching-label-pod.yaml
    
  - name: verify-no-job-creation
    try:
    - script:
        content: |
          #!/bin/bash
          # Check that no job was created for the non-matching pod
          JOBS=$(kubectl get jobs -l "triggered-by=non-matching-pod" -n default --no-headers | wc -l)
          if [ "$JOBS" -eq "0" ]; then
            echo "No jobs were created for non-matching pod as expected"
            exit 0
          else
            echo "Expected no jobs, but found $JOBS jobs"
            exit 1
          fi