apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eventtriggeredjobs.kubanana.roshanbhatia.com
spec:
  group: kubanana.roshanbhatia.com
  names:
    kind: EventTriggeredJob
    listKind: EventTriggeredJobList
    plural: eventtriggeredjobs
    singular: eventtriggeredjob
    shortNames:
    - etj
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            # Either eventSelector or statusSelector is required
            anyOf:
            - required: ["eventSelector"]
            - required: ["statusSelector"]
            # JobTemplate is always required
            required:
            - jobTemplate
            properties:
              eventSelector:
                type: object
                required:
                - resourceKind
                - eventTypes
                properties:
                  resourceKind:
                    type: string
                  namePattern:
                    type: string
                  namespacePattern:
                    type: string
                  labelSelector:
                    type: object
                    properties:
                      matchLabels:
                        type: object
                        additionalProperties:
                          type: string
                      matchExpressions:
                        type: array
                        items:
                          type: object
                          required:
                          - key
                          - operator
                          properties:
                            key:
                              type: string
                            operator:
                              type: string
                            values:
                              type: array
                              items:
                                type: string
                  eventTypes:
                    type: array
                    items:
                      type: string
                      enum:
                      - CREATE
                      - UPDATE
                      - DELETE
              statusSelector:
                type: object
                required:
                - resourceKind
                - conditions
                properties:
                  resourceKind:
                    type: string
                  namePattern:
                    type: string
                  namespacePattern:
                    type: string
                  labelSelector:
                    type: object
                    properties:
                      matchLabels:
                        type: object
                        additionalProperties:
                          type: string
                      matchExpressions:
                        type: array
                        items:
                          type: object
                          required:
                          - key
                          - operator
                          properties:
                            key:
                              type: string
                            operator:
                              type: string
                            values:
                              type: array
                              items:
                                type: string
                  conditions:
                    type: array
                    items:
                      type: object
                      required:
                      - type
                      - status
                      properties:
                        type:
                          type: string
                        status:
                          type: string
                        operator:
                          type: string
              jobTemplate:
                type: object
                x-kubernetes-preserve-unknown-fields: true
                description: "Standard Kubernetes job template to be created when matching events are detected"
          status:
            type: object
            properties:
              jobsCreated:
                type: integer
                format: int64
              lastTriggeredTime:
                type: string
                format: date-time
              conditions:
                type: array
                items:
                  type: object
                  required:
                  - type
                  - status
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    observedGeneration:
                      type: integer
                      format: int64
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
    subresources:
      status: {}