apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevent-controller
  namespace: kubevent-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevent-controller
rules:
- apiGroups: [""]
  resources: ["events", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["kubevent.roshanbhatia.com"]
  resources: ["EventTriggeredJob"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevent-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevent-controller
subjects:
- kind: ServiceAccount
  name: kubevent-controller
  namespace: kubevent-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevent-controller
  namespace: kubevent-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubevent-controller
  template:
    metadata:
      labels:
        app: kubevent-controller
    spec:
      serviceAccountName: kubevent-controller
      containers:
      - name: controller
        image: kubevent-controller:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi