apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: variable-substitution
spec:
  steps:
  - name: create-variable-job-template
    try:
    - apply:
        file: ../resources/variable-job-template.yaml
    - assert:
        file: ../resources/variable-job-template.yaml
  
  - name: create-test-pod-for-variables
    try:
    - apply:
        file: ../resources/test-pod-for-variables.yaml
    - assert:
        file: ../resources/test-pod-for-variables.yaml
    
  - name: verify-job-with-variables
    try:
    - assert:
        file: ../verifications/variable-job-created.yaml
  
  - name: verify-job-env-variables
    try:
    - script:
        content: |
          #!/bin/bash
          set -e
          kubectl get jobs -n default -l kubanana-resource-name=test-pod-for-variables | grep test-pod-for-variables
          # Get the pod name created by the job
          POD_NAME=$(kubectl get pods -n default -l job-name=$(kubectl get jobs -n default -l kubanana-resource-name=test-pod-for-variables -o jsonpath='{.items[0].metadata.name}') -o jsonpath='{.items[0].metadata.name}')
          # Wait for pod to complete
          kubectl wait --for=condition=Ready pod/$POD_NAME -n default --timeout=30s
          # Check logs for variable substitution
          kubectl logs $POD_NAME -n default | grep "Resource: Pod, Name: test-pod-for-variables"