apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  labels:
    kubanana-resource-kind: Pod
    kubanana-template: test-job-template
  ownerReferences:
  - apiVersion: kubanana.roshanbhatia.com/v1alpha1
    kind: EventTriggeredJob
    name: test-job-template
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command:
        - echo
        - "Hello from Kubanana!"
        env:
        - name: RESOURCE_KIND
          value: Pod
        - name: RESOURCE_NAME
        - name: RESOURCE_NAMESPACE
          value: default
        - name: EVENT_TYPE
          value: CREATE
      restartPolicy: Never