apiVersion: batch/v1
kind: Job
metadata:
  namespace: kubanana-system
  labels:
    kubanana-resource-kind: Pod
    kubanana-resource-namespace: prod-us-east1
    kubanana-template: namespace-pattern-job-template
  ownerReferences:
  - apiVersion: kubanana.roshanbhatia.com/v1alpha1
    kind: EventTriggeredJob
    name: namespace-pattern-job-template
spec:
  template:
    spec:
      containers:
      - name: echo
        image: busybox
        command:
        - sh
        - -c
        - echo 'Pod in prod namespace detected!'; sleep 5
        env:
        - name: RESOURCE_KIND
          value: Pod
        - name: RESOURCE_NAME
          value: prod-test-pod
        - name: RESOURCE_NAMESPACE
          value: prod-us-east1
        - name: EVENT_TYPE
          value: CREATE
      restartPolicy: Never