apiVersion: batch/v1
kind: Job
metadata:
  # This will look for any job in any namespace that has labels indicating it's from our status template
  labels:
    kubanana-resource-kind: Pod
    kubanana-trigger-type: status
check:
  existence: true