apiVersion: v1
kind: Pod
metadata:
  name: dev-test-pod
  namespace: dev-us-east1
  labels:
    app: "web-server"
    environment: "development"
spec:
  containers:
  - name: nginx
    image: nginx:latest
  restartPolicy: Never