apiVersion: kubanana.roshanbhatia.com/v1alpha1
kind: EventTriggeredJob
metadata:
  name: label-selector-job-template
  namespace: default
spec:
  eventSelector:
    resourceKind: "Pod"
    labelSelector:
      matchLabels:
        app: "monitored-app"
        environment: "test"
    eventTypes: ["CREATE"]
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: echo
            image: busybox
            command: ["sh", "-c", "echo 'Matching pod event detected!'; sleep 5"]
          restartPolicy: Never