apiVersion: v1
kind: Pod
metadata:
  name: matching-label-pod
  namespace: default
  labels:
    app: "monitored-app"
    environment: "test"
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "echo 'Pod with matching labels running'; sleep 60"]
  restartPolicy: Never