apiVersion: kubevent.roshanbhatia.com/v1alpha1
kind: EventTriggeredJob
metadata:
  name: namespace-pattern-job-template
  namespace: kubevent-system
spec:
  eventSelector:
    resourceKind: "Pod"
    namespacePattern: "prod-*"
    eventTypes: ["CREATE"]
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: echo
            image: busybox
            command: ["sh", "-c", "echo 'Pod created in production namespace: $RESOURCE_NAMESPACE'; sleep 5"]
          restartPolicy: Never