apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  labels:
    test: "kubevent"
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "echo 'Test pod running'; sleep 60"]
  restartPolicy: Never