name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm chart version
        run: make helm-update

      - name: Package Helm chart
        run: |
          mkdir -p charts/dist
          make helm-package

      - name: Push Docker image with version tag
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/controller:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}/controller:latest

      - name: Push Helm chart to GHCR
        run: |
          # Extract version from tag (remove 'v' prefix)
          VERSION=${GITHUB_REF_NAME#v}
          
          # Get packaged chart file
          CHART_PACKAGE=$(ls ./charts/dist/kubanana-*.tgz | head -n 1)
          
          # Push Helm chart to GHCR
          helm push ${CHART_PACKAGE} oci://ghcr.io/${{ github.repository }}/charts

          # Output success message
          echo "Successfully pushed Helm chart to ghcr.io/${{ github.repository }}/charts"