name: main-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Set up Kind 
      uses: engineerd/setup-kind@v0.6.2
      with:
        version: "v0.24.0"
        
    - name: Install Chainsaw
      uses: kyverno/action-install-chainsaw@v0.1.0
      with:
        release: v0.2.12
        
    - name: Install dependencies
      run: make deps docker-deps

    - name: Build (Go)
      run: make build-controller

    - name: Test (Go)
      run: make test

    - name: Build (Docker)
      run: make docker-build

    - name: Test (Chainsaw)
      run: make kind-setup chainsaw-test
      
